### ISSUE TITLE
Snowflake SQL Syntax Error 

### ISSUE THREAD

**Issue by Myron-Mosaad-Niche** [scottpersinger/pgwarehouse#5]
Hey! I was trying out this package for moving some tables from postgres to snowflake. I noticed there were two sql syntax errors where there is a duplicate "INTO" causing a silent error :
(https://github.com/scottpersinger/pgwarehouse/blob/d0a6d8b97e4fbfcb56cb03f4d175c7f5a99d4115/pgwarehouse/snowflake_backend.py#L146)
and 
(https://github.com/scottpersinger/pgwarehouse/blob/d0a6d8b97e4fbfcb56cb03f4d175c7f5a99d4115/pgwarehouse/snowflake_backend.py#L193)

I have the fix on a local branch if you would like me to push up and submit a PR.

**Comment by scottpersinger** [comment]
For sure! Send over a PR - thanks!

**Comment by scottpersinger** [comment]
thanks for doing some debugging, but those dupes are actually just in log lines, so shouldn't be impacting the actual operations.
