### ISSUE TITLE
support psycopg2 sslmode

### ISSUE THREAD

**Issue by MattMacGillivray** [scottpersinger/pgwarehouse#7]
Please support passing sslmode to psycopg2.  Most cloud databases require it, example change in pgwarehouse.py:

```
        self.pgsslmode = conf.get('pgsslmode', 'preferred')
        self.client = psycopg2.connect(
            f"host={self.pghost} dbname={self.pgdatabase} user={self.pguser} password={self.pgpassword} port={self.pgport} sslmode={self.pgsslmode}",
            connect_timeout=10
        )
```

**Comment by MattMacGillivray** [comment]
This PR addresses the problem, and more - https://github.com/scottpersinger/pgwarehouse/pull/8

**Comment by scottpersinger** [comment]
thanks Matt! I merged your PR. Funny that I wrote this thing against a Heroku db... Guess it didn't require SSL!
